ca:
   root:
      dn: CN=elasticsearch.ca.company.info,OU=CA,O=Company \, Inc.,DC=Company,DC=com
      keysize: 2048
      validityDays: 3650
      pkPassword: my-difficult-password
      file: root-ca.pem
defaults:
      validityDays: 3650
      pkPassword: my-difficult-password
      generatedPasswordLength: 12
      httpsEnabled: true
      reuseTransportCertificatesForHttp: true

nodes:
  - name: es-master1
    dn: CN=es-master1.company.info.com,OU=CA,O=Company \, Inc.,DC=Company,DC=com
  - name: es-master2
    dn: CN=es-master2.company.info.com,OU=CA,O=Company \, Inc.,DC=Company,DC=com
  - name: es-data1
    dn: CN=es-data1.company.info.com,OU=CA,O=Company \, Inc.,DC=Company,DC=com
  - name: es-data2
    dn: CN=es-data2.company.info.com,OU=CA,O=Company \, Inc.,DC=Company,DC=com
  - name: es-data3
    dn: CN=es-data3.company.info.com,OU=CA,O=Company \, Inc.,DC=Company,DC=com
